services:
  - type: web
    name: vnr-game-quiz
    env: static
    buildCommand: cd web && npm install && npm run build
    staticPublishPath: ./web/dist
    envVars:
      - key: VITE_SUPABASE_URL
        value: https://ualqdtjpwucvsqtfvdee.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: sb_publishable_0YjxTiyUMIuoygGqYzJA3w_47FpcZTv
